# Generated by Django 5.2.8 on 2025-11-06 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the agent session", max_length=200
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        default="gpt-4o-mini",
                        help_text="OpenAI model to use for this session",
                        max_length=100,
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        blank=True,
                        help_text="System prompt to configure agent behavior",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Agent Session",
                "verbose_name_plural": "Agent Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromptResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField(help_text="User's input prompt")),
                (
                    "response",
                    models.TextField(blank=True, help_text="AI generated response"),
                ),
                (
                    "model_used",
                    models.CharField(
                        default="gpt-4o-mini",
                        help_text="Model used for this response",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if processing failed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "processing_time",
                    models.FloatField(
                        blank=True,
                        help_text="Time taken to process in seconds",
                        null=True,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated agent session",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompts",
                        to="prompt_agent.agentsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prompt Response",
                "verbose_name_plural": "Prompt Responses",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="prompt_agen_created_31541d_idx"
                    ),
                    models.Index(
                        fields=["status"], name="prompt_agen_status_098a88_idx"
                    ),
                ],
            },
        ),
    ]
